// <auto-generated />
using System;
using JSL.Viagem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JSL.Viagem.Data.Migrations
{
    [DbContext(typeof(ViagemContext))]
    [Migration("20210702205725_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JSL.Viagem.Domain.Viagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHoraViajem")
                        .HasColumnType("datetime");

                    b.Property<double>("Km")
                        .HasColumnType("float");

                    b.Property<string>("LocalEntrega")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LocalSaida")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MotoristaId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Viagem");
                });
#pragma warning restore 612, 618
        }
    }
}
